// PAGINATION
export const PAGINATE_PAGE_DEFAULT = 1;
export const PAGINATE_TOTAL_DEFAULT = 1;
export const PAGINATE_PAGESIZE = 10;

// NAVBAR CONTEXT
export const OPEN_NAV_MENU = "OPEN_NAV_MENU";
export const CLOSE_NAV_MENU = "CLOSE_NAV_MENU";
export const COLLAPSE_NAV_MENU = "COLLAPSE_NAV_MENU";

// CRUD CONTEXT
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const OPEN_ADVANCED_BOX = "OPEN_ADVANCED_BOX";
export const CLOSE_ADVANCED_BOX = "CLOSE_ADVANCED_BOX";

export const OPEN_EDIT_BOX = "OPEN_EDIT_BOX";
export const CLOSE_EDIT_BOX = "CLOSE_EDIT_BOX";

export const OPEN_PANEL = "OPEN_PANEL";
export const CLOSE_PANEL = "CLOSE_PANEL";
export const COLLAPSE_PANEL = "COLLAPSE_PANEL";

export const OPEN_BOX = "OPEN_BOX";
export const CLOSE_BOX = "CLOSE_BOX";
export const COLLAPSE_BOX = "COLLAPSE_BOX";

export const OPEN_READ_BOX = "OPEN_READ_BOX";
export const CLOSE_READ_BOX = "CLOSE_READ_BOX";
export const COLLAPSE_READ_BOX = "COLLAPSE_READ_BOX";

// CRUD REDUX
export const RESET_STATE = "CRUD_RESET_STATE";
export const CURRENT_ITEM = "CRUD_CURRENT_ITEM";

export const REQUEST_LOADING = "CRUD_REQUEST_LOADING";
export const REQUEST_SUCCESS = "CRUD_REQUEST_SUCCESS";
export const REQUEST_FAILED = "CRUD_REQUEST_FAILED";
